apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: coffeebuddy-slack
proxy:
  protocol: https
  path: /
route:
  methods:
    - POST
  strip_path: false
  preserve_host: true
---
apiVersion: v1
kind: Service
metadata:
  name: coffeebuddy-slack
  labels:
    app: coffeebuddy
spec:
  selector:
    app: coffeebuddy
  ports:
    - name: http
      port: 8080
      targetPort: http